% fig_3_PCA.m
%
% This code generate the figure 3 (PCA)
% It requires the file "data_model_comparison.mat" which is available but
% can also be generated by "data_generation_model_comparison.m"

%% Load data
load data_model_comparison.mat

% res(1): WIL = Wilhelm & Suttle
% res(2): WEI = Weitz et al
% res(3): FUH = Fuhrman (2 datasets, 500 copies each)
% res(4): MOJ = Mojica & Brussaard (2 datasets, 500 copies each)
% res(5): XIE = Xie et al (2 datasets, 500 copies each)

%% Construct data matrix

% we take equal weighting for each of the 5 datasets
% fo WIL and WIE: 1000 realisations
% for others: 500 copies of each variant, so that 1000 copies in total

% The fluxes of the models are expressed as flux ratios (see Appendix S5)
X_data1 = zeros(0,10);
for cc=1:5
    x1 = zeros(length(res(cc).flx),10);
    x1(:,1) = arrayfun(@(s) s.mat(3,3)/s.mat(1,1), res(cc).flx);
    x1(:,2) = arrayfun(@(s) s.mat(4,4)/s.mat(1,1), res(cc).flx);
    x1(:,3) = arrayfun(@(s) s.mat(5,5)/s.mat(1,1), res(cc).flx);
    x1(:,4) = arrayfun(@(s) -s.mat(1,3)/s.mat(1,1), res(cc).flx);
    x1(:,5) = arrayfun(@(s) -s.mat(2,3)/s.mat(4,4), res(cc).flx);
    x1(:,6) = arrayfun(@(s) -s.mat(1,4)/s.mat(1,1), res(cc).flx);
    x1(:,7) = arrayfun(@(s) -s.mat(2,4)/s.mat(4,4), res(cc).flx);
    x1(:,8) = arrayfun(@(s) -s.mat(1,5)/s.mat(1,1), res(cc).flx);
    x1(:,9) = arrayfun(@(s) -s.mat(2,5)/s.mat(4,4), res(cc).flx);
    x1(:,10) = arrayfun(@(s) -s.mat(3,4)/s.mat(3,3), res(cc).flx);
    X_data1 = [X_data1; x1];
end

% Equal weights between the 5 models (=1000)
X_data2 = zeros(5000,10);
X_data2(1:1000,:) = X_data1(1:1000,:);
X_data2(1001:2000,:) = X_data1(1001:2000,:);
X_data2(2001:3000,:) = repmat(X_data1(2001:2002,:), 500, 1);
X_data2(3001:4000,:) = repmat(X_data1(2003:2004,:), 500, 1);
X_data2(4001:5000,:) = repmat(X_data1(2005:2006,:), 500, 1);

X_data = X_data2;
rngs = [
    1     1000;   
    1001  2000;   
    2001  3000;   
    3001  4000;   
    4001  5000];   

%% PCA

X_mean = mean(X_data, 1);
X_ctrd = X_data - X_mean;
[U, S, V] = svd(X_ctrd, 'econ');
scores = X_ctrd * V(:, 1:2);
loadings = V(:, 1:2);

%% Enforce PCA axes orientation

% (high PC2 => high viral lysis of bacteria)
if dot(scores(:,1), X_ctrd(:,8)) < 0
    V(:,1)        = -V(:,1);
    scores(:,1)   = -scores(:,1);
    loadings(:,1) = -loadings(:,1);
end

% (high PC2 => high viral lysis of bacteria)
if dot(scores(:,2), X_ctrd(:,9)) < 0
    V(:,2)        = -V(:,2);
    scores(:,2)   = -scores(:,2);
    loadings(:,2) = -loadings(:,2);
end

% The x- and y-axes of the PCA are inverted so that viral-induced fluxes 
% consistently show a positive correlation with the axes.

%%
eigvals = diag(S).^2;
explained = eigvals / sum(eigvals) * 100;

n = size(X_ctrd,1);
lambda = eigvals / (n-1);

% variables selected to be represented on the PCA
idx = [1 2 3 4 7 8 9]; % fGtot fDtot fVtot aPG aBD^0 aPD^V aBD^V

% we draw a circle to indicate importance of non-selected variables
% radius of this circle = longest arrow of non-selected variables
coords = V(:,1:2) .* sqrt(lambda(1:2)'); % PC1 and PC2
arrow_lengths = sqrt(sum(coords.^2, 2)); % arrow length
all_vars = 1:size(V,1);
not_idx = setdiff(all_vars, idx); % non-selected variables
missing_lengths = arrow_lengths(not_idx);
max_missing_length = max(missing_lengths); % longest arrow of non-selected variables


%%  Plotting subplot 1 
% Colors
cols = [
    244 162 97;  
    42 157 143;  
    231 111 81;   
    233 196 106; 
    0 109 119;  
] / 255;

clf

fig = gcf;
set(fig,'Units','centimeters')
set(fig,'Position',[2 2 50 18])  

ax1 = axes('Position',[0.08 0.15 0.55 0.75]); 
hold(ax1,'on')

for iModel = 1:5
    x = scores(rngs(iModel,1):rngs(iModel,2),1);
    y = scores(rngs(iModel,1):rngs(iModel,2),2);

    if iModel == 1   % WIL
        
        % determine KDE grid
        xrng = [min(x) max(x)];
        xrng = xrng + .2*diff(xrng)*[-1 1];
        xlin = linspace(xrng(1), xrng(2), 100);
        yrng = [min(y) max(y)];
        yrng = yrng + .2*diff(yrng)*[-1 1];
        ylin = linspace(yrng(1), yrng(2), 100);
        [Xgrid, Ygrid] = meshgrid(xlin, ylin);
        
        % compute KDE function
        ww = .02;
        zz = zeros(size(Xgrid));
        for ctr = 1:length(x)
            zz = zz+exp(-(Xgrid-x(ctr)).^2/2/ww^2 ...
                        -(Ygrid-y(ctr)).^2/2/ww^2);
        end
        
        % determine mode of KDE function
        [~, idxMax] = max(zz(:));
        x_mode = Xgrid(idxMax);
        y_mode = Ygrid(idxMax);
        
        % plot density lines
        contour(Xgrid, Ygrid, zz, 5, ...
            'LineColor', cols(iModel,:), 'LineWidth', 1.5);
        h = scatter(x_mode, y_mode, 150, cols(iModel,:), 'x', ...
            'LineWidth', 3, 'MarkerEdgeAlpha', 1);

    elseif iModel == 2   % WEI
        
        % determine KDE grid
        xrng = [min(x) max(x)];
        xrng = xrng + .2*diff(xrng)*[-1 1];
        xlin = linspace(xrng(1), xrng(2), 100);
        yrng = [min(y) max(y)];
        yrng = yrng + .2*diff(yrng)*[-1 1];
        ylin = linspace(yrng(1), yrng(2), 100);
        [Xgrid, Ygrid] = meshgrid(xlin, ylin);

        % compute KDE function
        ww = .03;
        zz = zeros(size(Xgrid));
        for ctr = 1:length(x)
            zz = zz+exp(-(Xgrid-x(ctr)).^2/2/ww^2 ...
                        -(Ygrid-y(ctr)).^2/2/ww^2);
        end

        % determine mode of KDE function
        [~, idxMax] = max(zz(:));
        x_mode = Xgrid(idxMax);
        y_mode = Ygrid(idxMax);
        
        % plot density lines
        contour(Xgrid, Ygrid, zz, 5, ...
            'LineColor', cols(iModel,:), 'LineWidth', 1.5);
        h = scatter(x_mode, y_mode, 150, cols(iModel,:), 'filled');
        
    elseif iModel == 5   % XIE
        h = scatter(x, y, 150, cols(iModel,:), 'filled');

    elseif ismember(iModel, [3 4])   % FUH & MOJ
        h = scatter(x, y, 150, cols(iModel,:), 'x', ...
            'MarkerEdgeColor', cols(iModel,:), ...
            'MarkerFaceAlpha', 0.1, 'LineWidth', 3);
    end
end

% Labels of variables
arrow = char(8594);
labs = {'f^{tot}_G','f^{tot}_D','f^{tot}_V', ...
    'a_{PG}','a_{BG}', 'a^{0}_{PD}','a^{0}_{BD}', ...
    'a^{V}_{PD}','a^{V}_{BD}', 'a_{GD}'};
for i = idx
    quiver(0, 0, loadings(i,1), loadings(i,2), ...
        'Color',[.3 .3 .3], 'LineWidth',1.5);
    if i == 1
        text(loadings(i,1), loadings(i,2)+0.05, labs{i}, ...
            'Color',[.3 .3 .3], 'FontSize',16);
    elseif i == 4
        text(loadings(i,1), loadings(i,2)-0.05, labs{i}, ...
            'Color',[.3 .3 .3], 'FontSize',16);
    elseif i == 7
        text(loadings(i,1), loadings(i,2)-0.05, labs{i}, ...
            'Color',[.3 .3 .3], 'FontSize',16);
    else
        text(loadings(i,1), loadings(i,2), labs{i}, ...
            'Color',[.3 .3 .3], 'FontSize',16);
    end
end

% Labels of models
% WIL
text(scores(rngs(1,1),1)-0.2, scores(rngs(1,1),2)+0.07, 'WIL', ...
    'Color', cols(1,:), 'FontSize', 13, 'FontWeight', 'bold');
% WEI
text(scores(rngs(2,1),1)+0.1, scores(rngs(2,1),2)+0.3, 'WEI', ...
    'Color', cols(2,:), 'FontSize', 13, 'FontWeight', 'bold');
% FUH
text(scores(rngs(3,1),1)-0.2, scores(rngs(3,1),2)+0.01, 'FUH-B', ...
    'Color', cols(3,:), 'FontSize', 13, 'FontWeight', 'bold');
text(scores(rngs(3,2),1)-0.2, scores(rngs(3,2),2)+0.06, 'FUH-BP', ...
    'Color', cols(3,:), 'FontSize', 13, 'FontWeight', 'bold');
% MOJ
text(scores(rngs(4,1),1)+0.03, scores(rngs(4,1),2)+0.05, 'MOJ-S', ...
    'Color', cols(4,:), 'FontSize', 13, 'FontWeight', 'bold');
text(scores(rngs(4,2),1)-0.1, scores(rngs(4,2),2)-0.07, 'MOJ-N', ...
    'Color', cols(4,:), 'FontSize', 13, 'FontWeight', 'bold');
% XIE
text(scores(rngs(5,1),1)-0.12, scores(rngs(5,1),2)-0.05, 'XIE-H', ...
    'Color', cols(5,:), 'FontSize', 13, 'FontWeight', 'bold');
text(scores(rngs(5,2),1)-0.13, scores(rngs(5,2),2)-0.05, 'XIE-A', ...
    'Color', cols(5,:), 'FontSize', 13, 'FontWeight', 'bold');

% 0-0 axes
plot([-1 2],[0 0], ':', 'Color','k', 'LineWidth', 1)
plot([0 0],[-1 1],':', 'Color','k', 'LineWidth', 1)

% Draw the circle: not represented variables
theta = linspace(0, 2*pi, 200);
r = max_missing_length;  % radius = longest arrow length
x_circ = r * cos(theta);
y_circ = r * sin(theta);
plot(x_circ, y_circ, '--', 'Color', [0.5 0.5 0.5], 'LineWidth', 1.5);
fill(r * cos(theta), r * sin(theta), [0.8 0.8 0.8], ...
        'FaceAlpha', 0.4, 'EdgeColor', 'none');

xlim([-1 1.5])
ylim([-0.5 0.75])
xticks(-1:0.5:1.5)
yticks(-1.5:0.5:1.5)

xlabel(sprintf('PC1 (%.0f%%)', explained(1)));
ylabel(sprintf('PC2 (%.0f%%)', explained(2)));
set(ax1, 'Box','on','XGrid','on','YGrid','on','FontSize',14)

axes(ax1)
text(0.025, 0.96, 'A', 'Units','normalized', ...
    'FontSize', 24, 'FontWeight','bold')

%%  Plotting subplot 2

% Extracting viral lysis fluxes
lysis_flx = [];

for i = 1:numel(res)
    if isfield(res(i), 'flx')
        for j = 1:numel(res(i).flx)
            lysis_flx(end+1,1) = res(i).flx(j).mat(5,5);
        end
    end
end

X_data1 = lysis_flx;

% Equal weights between the 5 models (=1000)
X_data2 = zeros(5000,1);
X_data2(1:1000,:)   = X_data1(1:1000,:);
X_data2(1001:2000,:) = X_data1(1001:2000,:);
X_data2(2001:3000,:) = repmat(X_data1(2001:2002,:), 500, 1);
X_data2(3001:4000,:) = repmat(X_data1(2003:2004,:), 500, 1);
X_data2(4001:5000,:) = repmat(X_data1(2005:2006,:), 500, 1);
X_data = X_data2;

rngs = [
    1     1000;   
    1001  2000;   
    2001  3000;   
    3001  4000;   
    4001  5000];

ax2 = axes('Position',[0.70 0.15 0.25 0.75]);  
hold(ax2,'on')

order = [5,1,3,4,2]; % reordering models
xpos = 1:length(order);

for idx = 1:length(order)
    m = order(idx);
    x = xpos(idx);

    if m <= 2
        % WIL and WEI: full violins
        data = X_data(rngs(m,1):rngs(m,2));
        [f, xi] = ksdensity(data);
        f = f / max(f) * 0.4;
        fill([x - f, fliplr(x + f)], [xi, fliplr(xi)], cols(m,:), 'FaceAlpha',0.5,'EdgeColor','none');
        plot([x x], [min(xi) max(xi)], 'w-', 'LineWidth',1);
        % find mode for 1D KDE
        [~, idxMax] = max(f);
        mode_y = xi(idxMax);
        if m==1
            scatter(x, mode_y, 150, cols(m,:), 'x', 'LineWidth', 3, 'MarkerEdgeAlpha', 1);
        elseif m==2
            scatter(x, mode_y, 150, cols(m,:), 'filled');
        end

    else
        % FUH, MOJ, XIE: scatter points using original vs indices
        if m == 3       % FUH
            scatter(x, X_data1(2001,1), 150, 'x', 'MarkerEdgeColor', cols(3,:), 'MarkerFaceAlpha', 0.1, 'LineWidth', 3);
            scatter(x, X_data1(2002,1), 150, 'x', 'MarkerEdgeColor', cols(3,:), 'MarkerFaceAlpha', 0.1, 'LineWidth', 3);
        elseif m == 4   % MOJ
            scatter(x, X_data1(2003,1), 150, 'x', 'MarkerEdgeColor', cols(4,:), 'MarkerFaceAlpha', 0.1, 'LineWidth', 3);
            scatter(x, X_data1(2004,1), 150, 'x', 'MarkerEdgeColor', cols(4,:), 'MarkerFaceAlpha', 0.1, 'LineWidth', 3);
        elseif m == 5   % XIE
            scatter(x, X_data1(2005,1), 150, cols(5,:), 'filled');
            scatter(x, X_data1(2006,1), 150, cols(5,:), 'filled');
        end
    end
end

% Legends of the models
% XIE
text(xpos(1)-0.3, X_data1(2005,1)+9, 'XIE-H', 'Color', cols(5,:), 'FontSize', 13, 'FontWeight', 'bold')
text(xpos(1)-0.3, X_data1(2006,1)+5, 'XIE-A', 'Color', cols(5,:), 'FontSize', 13, 'FontWeight', 'bold')
% FUH
text(xpos(3)-0.3, X_data1(2001,1)-5, 'FUH-B', 'Color', cols(3,:), 'FontSize', 13, 'FontWeight', 'bold')
text(xpos(3)-0.3, X_data1(2002,1)+5, 'FUH-BP', 'Color', cols(3,:), 'FontSize', 13, 'FontWeight', 'bold')
% MOJ
text(xpos(4)-0.3, X_data1(2003,1)+5, 'MOJ-S', 'Color', cols(4,:), 'FontSize', 13, 'FontWeight', 'bold')
text(xpos(4)-0.3, X_data1(2004,1)+5, 'MOJ-N', 'Color', cols(4,:), 'FontSize', 13, 'FontWeight', 'bold')

% Axes ticks, labels, and limits
xticks(xpos)
xticklabels({'XIE','WIL','FUH','MOJ','WEI'})
ylabel('Lysis percentage $\mathcal{L}^{\mathrm{flux}}$','Interpreter','latex')
xlim([0.5 5.5])
ylim([0 125])
set(gca, 'FontSize',14,'Box','on','XGrid','on','YGrid','on')
ax2 = gca;

daspect(ax2,'auto');

axes(ax2)
text(0.05, 0.96, 'B', 'Units','normalized', ...
    'FontSize', 24, 'FontWeight','bold')

%% Save figure

exportgraphics(gcf, 'fig3_pca.pdf', 'ContentType','vector','BackgroundColor','none');
