function [dx,ph] = wei_rhs(x,p)
% function [dx,ph] = wei_rhs(x,p)
% Computing dynamical equations from Weitz et al. 2015
%
% Inputs:
% . x : equilibria values
% . p : parameters
%
% Outputs: 
% . dx : dynamical equations in abundance units from Weitz et al. 2015
% . ph : flux matrix, dimensions 10x10 (row/column 10 is the virus-driven DOC)

%% Equilibria

H=x(1); %Heterotrophs
C=x(2); %Cyanobacteria
E=x(3); %Eukaryotic autotrophs
Z=x(4); %Zooplakton
VH=x(5); %Viruses of H
VC=x(6); %Viruses of C
VE=x(7); %Viruses of E
xo=x(8); %Organic nitrogen
xi=x(9); %Inorganic nitrogen

%% Dynamics

ph = zeros(9,10);
% Dynamics of H
ph(1,:) = [p.muH*H*xo/(xo+p.Ko) 0 0 ...
           -p.pg*p.psH*H*Z ...
           -p.qV*p.beH/p.qH*p.phH*H*VH 0 0 ...
           -p.moH*H-p.po*p.psH*H*Z ...
           -p.miH*H-p.pi*p.psH*H*Z ...
           -(1-p.qV*p.beH/p.qH)*p.phH*H*VH];
dH = sum(ph(1,:));

% Dynamics of C
ph(2,:) = [0 p.muC*C*xi/(xi+p.KiC) 0 ...
           -p.pg*p.psC*C*Z ...
           0 -p.qV*p.beC/p.qC*p.phC*C*VC 0 ...
           -p.moC*C-p.po*p.psC*C*Z ...
           -p.miC*C-p.pi*p.psC*C*Z ...
           -(1-p.qV*p.beC/p.qC)*p.phC*C*VC];
dC = sum(ph(2,:));

% Dynamics of E
ph(3,:) = [0 0 p.muE*E*xi/(xi+p.KiE) ...
           -p.pg*p.psE*E*Z ...
           0 0 -p.qV*p.beE/p.qE*p.phE*E*VE ...
           -p.moE*E-p.po*p.psE*E*Z ...
           -p.miE*E-p.pi*p.psE*E*Z ...
           -(1-p.qV*p.beE/p.qE)*p.phE*E*VE];
dE= sum(ph(3,:));

% Dynamics of Z
ph(4,:) = [0 0 0 ...
           p.pg/p.qZ*(p.qH*p.psH*H*Z+p.qC*p.psC*C*Z+p.qE*p.psE*E*Z) ...
           0 0 0 ...
           0 -p.mZ*Z 0];
dZ = sum(ph(4,:))-p.mZP*Z^2;

% Dynamics of VH
ph(5,:) = [0 0 0 0 ...
           p.beH*p.phH*H*VH 0 0 ...
           -p.mVH*VH 0 0];
dVH = sum(ph(5,:));

% Dynamics of VC
ph(6,:) = [0 0 0 0 ...
           0 p.beC*p.phC*C*VC 0 ...
           -p.mVC*VC 0 0];
dVC = sum(ph(6,:));

% Dynamics of VE
ph(7,:) = [0 0 0 0 ...
           0 0 p.beE*p.phE*E*VE ...
           -p.mVE*VE 0 0];
dVE = sum(ph(7,:));

% Dynamics of xo
ph(8,:) = [-p.qH*p.muH*H*xo/(xo+p.Ko) ...
           0 0 0 0 0 0 ...
           p.qV*p.mVH*VH + p.qV*p.mVC*VC + p.qV*p.mVE*VE + ...
           (p.qH-p.qV*p.beH)*p.phH*H*VH + ...
           (p.qC-p.qV*p.beC)*p.phC*C*VC + ...
           (p.qE-p.qV*p.beE)*p.phE*E*VE + ...
           p.qH*p.moH*H + p.qC*p.moC*C + p.qE*p.moE*E + ...
           p.po*p.qH*p.psH*H*Z + ...
           p.po*p.qC*p.psC*C*Z + ...
           p.po*p.qE*p.psE*E*Z ...
           -p.qH*(1-p.eH)/p.eH*p.muH*H*xo/(xo+p.Ko) 0];
dxo = sum(ph(8,:));

% Dynamics of xi
ph(9,:) = [0 -p.qC*p.muC*C*xi/(xi+p.KiC) -p.qE*p.muE*E*xi/(xi+p.KiE) ...
           0 0 0 0 0 ...
           -p.omg*(xi-p.xsb) + ...
           p.qH*(1-p.eH)/p.eH*p.muH*H*xo/(xo+p.Ko) + ...
           p.qZ*p.mZ*Z + p.qH*p.miH*H + p.qC*p.miC*C + p.qE*p.miE*E + ...
           p.pi*p.qH*p.psH*H*Z + ...
           p.pi*p.qC*p.psC*C*Z + ...
           p.pi*p.qE*p.psE*E*Z 0];
dxi = sum(ph(9,:));

dx=[dH;dC;dE;dZ;dVH;dVC;dVE;dxo;dxi];

% Conversion into carbon fluxes
ph = diag([p.qH p.qC p.qE p.qZ p.qV p.qV p.qV 1 1])*ph;

% Virus-driven DOC
aux = -sum(ph(:,end));
ph(10,[8 10]) = [-aux aux];

end
