function [dx,ph] = virusremoval_model_rhs(x,p)
% function [dx,pħ] = virusremoval_model_rhs(x,p)
%
% Evaluates the right-hand side of the dynamical equations of
% the minimal marine microbial ecosystem model
%
% Inputs:
% . x : system state (vector of length 6)
% . p : parameters (stucture with 26 fields)
%
% Outputs:
% . dx : right-hand side of dynamical equations
% . ph : right-hand side written as flux matrix
%
% Notes:
% . The order of the variables in the state vector is
%     P, B, G, VP, VB, D
% . The fluxes in matrix ph are the following:
%     [   FP      0   -FPG   -FPV      0 -FPD^0 -FPD^V   -FP0
%          0     FB   -FBG      0   -FBV -FBD^0 -FBD^V   -FB0
%          0      0     FG      0      0   -FGD      0   -FG0
%          0      0      0    FVP      0  -FVPD      0      0
%          0      0      0      0    FVB  -FVBD      0      0
%          0    -FDB     0      0      0     FD      0   -FD0  ]

P  = x(1);
B  = x(2);
G  = x(3);
VP = x(4);
VB = x(5);
D  = x(6);

% Growth rates
muP = p.muP_max*(1 - P/p.KP);
muB = p.muB_max*D/(p.KDB + D);

% Phytoplankton
ph(1,:) = [muP*P  0 ...
           -p.pG_assim*p.psiPG*P*G ...
           -p.phiP*P*VP*p.qV/p.qP*p.betaP  0 ...
           -p.lP_org*P-p.pG_org*p.psiPG*P*G ...
           -p.phiP*P*VP*(1-p.qV/p.qP*p.betaP) ...
           -p.lP_inorg*P-(1-p.pG_assim-p.pG_org)*p.psiPG*P*G];
dP = muP*P -p.psiPG*P*G -p.phiP*P*VP ...
    -p.lP_inorg*P -p.lP_org*P;

% Bacteria
ph(2,:) = [0  muB*B ...
           -p.pG_assim*p.psiBG*B*G ...
           0  -p.phiB*B*VB*p.qV/p.qB*p.betaB ...
           -p.lB_org*B-p.pG_org*p.psiBG*B*G ...
           -p.phiB*B*VB*(1-p.qV/p.qB*p.betaB) ...
           -p.lB_inorg*B-(1-p.pG_assim-p.pG_org)*p.psiBG*B*G];
dB = muB*B -p.psiBG*B*G -p.phiB*B*VB ...
    -p.lB_inorg*B -p.lB_org*B;

% Grazers
ph(3,:) = [0  0  ...
           p.pG_assim*p.psiPG*G*P*p.qP/p.qG + ...
             p.pG_assim*p.psiBG*G*B*p.qB/p.qG ...
           0  0  ...
           -p.lG_cons*G^2  0  -p.lG_inorg*G];
dG = p.pG_assim*p.psiPG*P*G*p.qP/p.qG ...
    +p.pG_assim*p.psiBG*B*G*p.qB/p.qG ...
    -p.lG_inorg*G -p.lG_cons*G^2;

%% Phytoplankton viruses
ph(4,:) = [0  0  0  p.betaP*p.phiP*P*VP  0  -p.lVP*VP  0  0];
dVP = p.betaP*p.phiP*P*VP -p.lVP*VP;

%% Bacterial viruses
ph(5,:) = [0  0  0  0  p.betaB*p.phiB*B*VB  -p.lVB*VB  0  0];
dVB = p.betaB*p.phiB*B*VB -p.lVB*VB;

%% DOC
ph(6,:) = [0  -p.qB*muB*B  0  0  0 ...
           p.lP_org*P*p.qP + p.lB_org*B*p.qB + ...
             p.lG_cons*G^2*p.qG + ...
             p.lVP*VP*p.qV + p.lVB*VB*p.qV + ...
             (p.qP-p.qV*p.betaP)*p.phiP*P*VP + ...
             (p.qB-p.qV*p.betaB)*p.phiB*B*VB + ...
             p.pG_org*p.psiPG*P*G*p.qP + ...
             p.pG_org*p.psiBG*B*G*p.qB  0 ...
           -(1/p.pDB_assim-1)*p.qB*muB*B];
dD = p.pG_org*p.psiPG*P*G*p.qP +p.lP_org*P*p.qP ...
    +p.pG_org*p.psiBG*B*G*p.qB +p.lB_org*B*p.qB ...
    +p.lG_cons*G^2*p.qG +p.lVP*VP*p.qV +p.lVB*VB*p.qV ...
    +p.phiP*P*VP*(p.qP-p.betaP*p.qV) ...
    +p.phiB*B*VB*(p.qB-p.betaB*p.qV) ...
    -1/p.pDB_assim*muB*B*p.qB;

dx = [dP;dB;dG;dVP;dVB;dD];

end
